#!/bin/sh

# shellcheck source=spec/support/docker/__fail_if_wrong_pwd.sh
. "$(dirname "$0")/__fail_if_wrong_pwd.sh"

# --pull=never is not supported in old docker versions
docker inspect esearch-rspec 1>/dev/null 2>&1 || \
  ( echo "The image needs to be built first " && exit 1 )

# Similar to what docker-compose.yml defines, but without introducing composer
# as a dependency.
# Does:
#   - Sets non-root uid:gid (for fixtures generation, taking screenshots etc.)
#   - Mounts a volume to allow interacting with changes without rebuilds
#   - Forwards ENV variables from HOST

set -ex;
# shellcheck disable=SC2086
exec docker run --rm -u "$(id -u):$(id -g)" -v "$PWD:/app" \
  -e "DANGEROUSLY_MAXIMIZE_PERFORMANCE=$DANGEROUSLY_MAXIMIZE_PERFORMANCE" \
  -e "SKIP_COMPATIBILITY_REGEXPS=$SKIP_COMPATIBILITY_REGEXPS" \
  -e "EDITOR_THROTTLE_INTERVAL=$EDITOR_THROTTLE_INTERVAL" \
  -e "SCREENSHOT_FAILURES=$SCREENSHOT_FAILURES" \
  -e "LOG_LEVEL=$LOG_LEVEL" \
  -e "GUI=$GUI" \
  -e "VIM_GUI=$VIM_GUI" \
  -e "NVIM_GUI=$NVIM_GUI" \
  -e "TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID" \
  -e "RUN_VNC=$RUN_VNC" \
  -e "NVIM_PATH=$NVIM_PATH" \
  -e "VIM_PATH=$VIM_PATH" \
  -e "PT_PATH=$PT_PATH" \
  -e "RG_PATH=$RG_PATH" \
  $DOCKER_RUN_ARGS_OVERRIDES  \
  -it esearch-rspec "$@"
