#!/bin/sh

# --pull=never is not supported in old docker versions
docker inspect esearch-provision-bats 2>&1 1>/dev/null || \
  ( echo "The image needs to be built first " && exit 1 )

docker run --rm \
  -v "$(realpath "$(dirname "$0")/../"):/provision:ro" \
  -it esearch-provision-bats "$@"
