#!/bin/sh

# --pull=never is not supported in old docker versions
docker inspect esearch-provision-bats 1>/dev/null 2>&1 || \
  ( echo "The image must be built first " && exit 1 )

docker run --rm \
  -v "$(realpath "$(dirname "$0")/../"):/provision:ro" \
  -it esearch-provision-bats "$@"
